# Generated by Django 4.1.2 on 2022-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scalp',
            name='user',
        ),
        migrations.AddField(
            model_name='scalp',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
