# Generated by Django 4.1.2 on 2022-12-08 16:18

from django.db import migrations, models
import telo.models


class Migration(migrations.Migration):

    dependencies = [
        ('telo', '0002_remove_scalp_user_scalp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalp',
            name='image',
            field=models.ImageField(null=True, upload_to=telo.models.image_name),
        ),
    ]
